### ISSUE TITLE
NPC does not give Objectives..

### ISSUE THREAD

**Issue by devkuros** [AlessioGr/NotQuests#214]
Why i can't start quest from conversations with NPC? 
all you invite link discord is invalid, so i asked here..

> conversations
> ![1](https://github.com/AlessioGr/NotQuests/assets/88880298/90b42b8a-62c7-4098-8a8c-ffda5fa8a794)

> action
> ![2](https://github.com/AlessioGr/NotQuests/assets/88880298/e37b9197-61ac-4ced-a8ff-5343b764e085)

for quest
```
quests:
  TutorialQuest:
    displayName: Tutorial Quest
    description: This Tutorial Quest
    objectives:
      "1":
        objectiveType: BreakBlocks
        progressNeededExpression: "10"
        specifics:
          itemStackSelection:
            materials:
              "1": DIRT
            any: false
          deductIfBlockPlaced: true
        description: bring Dirt 10 
        displayName: Getting Started
    rewards:
      "1":
        actionType: Number
        specifics:
          expression: "1"
          variableName: QuestPoints
          operator: add
          additionalBooleans:
            notifyPlayer: "0.0"
        displayName: +1 Quest Point
    takeEnabled: false
    npcs:
      citizens-1:
        npcData:
          type: citizens
          name: Ghera
          integerID: 1
        questShowing: true
    abortEnabled: false
```
